#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CURRENT_DIR=`pwd`

rm -rf /tmp/app
mkdir -p /tmp/app
cp -R ${DIR} /tmp/app

cd /tmp/app/BS

echo "Changing parameters ..."
sed -i -e 's/ private final int nTileSize = 16;/ private int nTileSize = 256;/g' src/main/java/es/bsc/mobile/apps/bs/Params.java
sed -i -e 's/ private final int outSizeI = 512;/ private int outSizeI = 1024;/g' src/main/java/es/bsc/mobile/apps/bs/Params.java
sed -i -e 's/ private final int outSizeJ = 512;/ private int outSizeJ = 1024;/g' src/main/java/es/bsc/mobile/apps/bs/Params.java

echo "Compiling application"
mvn -q -o -Dmaven.test.skip=true clean
mvn -q -o -Dmaven.test.skip=true compile
mvn -q -o -Dmaven.test.skip=true package

echo "Preparing logcat"
adb logcat -c
time=`adb shell "date +\"%m-%d %H:%M:%S.000\"" |cut -c1-18`
/usr/bin/konsole --new-tab --hold -e adb logcat -v raw -T "${time}" System.out:V *:S
mvn android:deploy
mvn android:run

cd ${CURRENT_DIR}
